import { isParkingCourse, type CourseDefinition } from './courses/course-definition';
import { RIGHT_ANGLE } from './courses/right-angle';
import { VEHICLE } from './vehicle-config';
import type { ExamSession } from './exam-session';
export function courseDiagram(course:CourseDefinition=RIGHT_ANGLE){
 const b=course.bounds, scale=Math.min(250/(b.maxX-b.minX),240/(b.maxZ-b.minZ));
 const x=(v:number)=>30+(v-b.minX)*scale, z=(v:number)=>30+(v-b.minZ)*scale;
 const project=(p:{x:number;z:number})=>`${x(p.x)},${z(p.z)}`;
 const line=([a,b]:CourseDefinition['finish'],color='currentColor',width=2,dashed=false)=>`<line x1="${x(a.x)}" y1="${z(a.z)}" x2="${x(b.x)}" y2="${z(b.z)}" stroke="${color}" stroke-width="${width}" ${dashed?'stroke-dasharray="5 5"':''}/>`;
 const parking=isParkingCourse(course),roads=parking?course.roads:[course.polygon];
 const startLabel=course.id==='reverse-garage'?'起点 →':'起点 ↑';
 const finish=course.finish[1];
 return `<svg class="course-diagram" viewBox="0 0 310 310" role="img" aria-label="${course.name}道路俯视示意。${course.description} ${course.dimensions}">${roads.map((road,i)=>`<polygon points="${road.map(project).join(' ')}" fill="${i?'#b5cbbd':'#d5ded6'}"/>`).join('')}${parking?course.penaltyLines.map(({segment,reason})=>line(segment,reason.startsWith('碰擦')?'#aa7527':'currentColor')).join('')+course.guides.map(edge=>line(edge,'#aa7527',1.5,true)).join('')+`<text x="${x((course.parkZone.minX+course.parkZone.maxX)/2)}" y="${z((course.parkZone.minZ+course.parkZone.maxZ)/2)}" text-anchor="middle" fill="#267447" font-size="20">↑</text>`:course.boundaries.map(edge=>line(edge)).join('')+`<polyline points="${course.center.map(project).join(' ')}" fill="none" stroke="currentColor" stroke-width="1.5" stroke-dasharray="5 6"/>`}${line(course.startMark,'#267447',3)}${line(course.finish,'#267447',3)}<rect x="${x(course.start.x)-5}" y="${z(course.start.z)-9}" width="10" height="18" rx="3" fill="#267447"/><text x="${x(course.start.x)+(course.id==='reverse-garage'?-4:14)}" y="${z(course.start.z)+(course.id==='reverse-garage'?-16:6)}">${startLabel}</text><text x="${x(finish.x)+(course.id==='reverse-garage'?-35:-25)}" y="${z(finish.z)+(course.id==='parallel-parking'?19:-12)}">终点</text></svg>`;
}
export class ExamUi {
 readonly overlay=document.createElement('section');
 readonly hud=document.createElement('section');
 private focusFrame=0;
 constructor(private session:ExamSession, private action:(name:string)=>void){
  this.overlay.id='exam-overlay';this.overlay.setAttribute('aria-label','考试流程');
  this.hud.id='exam-hud';
  document.querySelector('#app')!.append(this.overlay,this.hud);
  for(const el of [this.overlay,this.hud])el.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-exam]');if(button&&!button.disabled)this.action(button.dataset.exam!);});
  this.render();
 }
 render(){
  cancelAnimationFrame(this.focusFrame);
  const s=this.session, course=s.course, practice=s.mode==='practice';document.body.dataset.exam=s.state;document.body.dataset.mode=s.mode;
  this.overlay.hidden=s.state==='running';this.hud.hidden=!s.active;
  if(s.state==='projects'||s.state==='briefing')this.overlay.scrollTop=0;
  this.hud.innerHTML=`<div><span class="eyebrow">${practice?'FREE DRIVE / 05':`ASSESSMENT / ${course.number}`}</span><strong>${practice?'自由练习':course.name} <span>${s.state==='paused'?'已暂停':practice?'自由驾驶中':'考试中'}</span></strong>${!practice&&isParkingCourse(course)?`<div class="parking-status" aria-live="off"><span>剩余 <b data-parking="remaining">30.0</b>s</span><span>库外停 <b data-parking="stopped">0.0</b>/2.0s</span><span>入库 <b data-parking="count">0</b>/${course.requiredParks}</span>${course.direction==='strict'?'<span>阶段 <b data-parking="phase">1/5 前进</b></span>':''}</div>`:''}</div><div class="exam-actions"><button data-exam="pause">暂停</button><button data-exam="retry">${practice?'复位':'重试'}</button><button data-exam="exit">退出</button></div>`;
  const btn=(action:string,label:string,primary=false)=>`<button class="${primary?'exam-primary':'exam-secondary'}" data-exam="${action}">${label}</button>`;
  if(s.state==='projects')this.overlay.innerHTML=`<div class="project-page"><div class="exam-eyebrow">LARRIA / DRIVING ACADEMY</div><div class="project-heading"><div><h1>把每一个转弯，<br>练成从容。</h1><p>从驾驶座出发，感受车身与道路的距离。<br>选择练习项目，开始你的科目二模拟考试。</p></div><span class="season-note">科目二 · 场地驾驶<br>CHAPTER 01 — PRECISION</span></div><div class="project-grid"><button class="project-feature" data-exam="select"><div><span class="card-number">01 / 已开放</span><h2>直角转弯</h2><p>把握转向时机，一次顺畅通过。</p><span class="project-link">查看考前说明 <b>↗</b></span></div>${courseDiagram()}</button><div class="upcoming-grid">${`<button class="project-placeholder project-available" data-exam="select:s-curve"><span class="card-number">02 / 已开放</span><h3>曲线行驶</h3><p>在连续弯道中感受方向</p><span>查看考前说明 ↗</span></button>`}${[['03','侧方位停车','掌握车位与车身的距离','parallel-parking'],['04','倒车入库','建立后视镜中的空间感','reverse-garage'],['05','自由练习','自由探索，熟悉驾驶操作','practice']].map(([n,title,desc,id])=>`<button class="project-placeholder project-available" data-exam="select:${id}"><span class="card-number">${n} / 已开放</span><h3>${title}</h3><p>${desc}</p><span>查看${id==='practice'?'练习':'考前'}说明 ↗</span></button>`).join('')}</div></div><div class="project-bottom">真实 3D 座舱 · 实时后视镜 · 支持键盘与触控<span>练习模拟，不代替正规驾驶培训</span></div></div>`;
  if(s.state==='briefing'&&practice)this.overlay.innerHTML=`<div class="briefing-page practice-briefing"><div class="exam-eyebrow">BEFORE YOU DRIVE / 05</div><div class="briefing-top"><div><h1>自由练习</h1><p class="exam-lead">没有考核，按自己的节奏熟悉驾驶。</p></div><div class="briefing-top-actions">${btn('exit','返回项目')}${btn('start','开始自由练习 →',true)}</div></div><div class="briefing-grid"><div class="diagram-panel practice-panel"><span class="exam-eyebrow">OPEN COURT / 自由场地</span><div class="practice-map" role="img" aria-label="开放练车场，地面设有引导停车格与虚线，不设终点或判罚边界"><span>自由练车区</span><span>引导停车格 · 无终点</span></div><p>开阔场地 · 地面标线仅用于辅助观察，不参与判罚。</p></div><div><h2>想怎么练，就怎么开。</h2><p>可自由前进、刹停、倒车和换挡，也可以尝试视角、方向盘与后视镜。停车格是辅助标记，不是考试项目。</p><ol class="exam-rules"><li><b>不设考试规则与时限</b><span>不会计分、判定通过或失败，也没有停车或倒库次数限制。</span></li><li><b>刹停后切换行驶方向</b><span>挂 D 档前进、R 档倒车、N 档空挡；行驶中仍须遵守换挡保护。</span></li><li><b>随时暂停或复位</b><span>暂停冻结车辆，继续后重新按下驾驶键；复位回到练习起点，退出返回项目。</span></li></ol><p class="vehicle-spec">Ferrari 458 Italia · 当前模拟配置<br>车身 ${VEHICLE.length.toFixed(2)} × ${VEHICLE.width.toFixed(2)} m · 轴距 ${VEHICLE.wheelbase.toFixed(3)} m<br><small>模型配套物理参数，非厂家标定数据。</small></p></div></div><div class="briefing-controls"><span><kbd>W</kbd> 油门　<kbd>S</kbd> 刹车　<kbd>A</kbd><kbd>D</kbd> 转向<br><kbd>Z</kbd> R 档　<kbd>X</kbd> N 档　<kbd>C</kbd> D 档</span><span>默认驾驶座舱 · 鼠标悬停转头；点“锁定环视”连续转头，Esc 先解锁<br>点击“回正视角”或双击场景回正；离开窗口自动暂停。</span></div></div>`;
  if(s.state==='briefing'&&!practice)this.overlay.innerHTML=`<div class="briefing-page"><div class="exam-eyebrow">BEFORE YOU DRIVE / ${course.number}</div><div class="briefing-top"><div><h1>${course.name}</h1><p class="exam-lead">看清规则，再从容出发。</p></div><div class="briefing-top-actions">${btn('exit','返回项目')}${btn('start','准备好了，开始考试 →',true)}</div></div><div class="briefing-grid"><div class="diagram-panel">${courseDiagram(course)}<p>${course.dimensions}</p></div><div><h2>${isParkingCourse(course)?'看准车位，稳稳入库。':course.id==='s-curve'?'连续转弯，同样从容。':'一次转弯，三条准则。'}</h2><p>${course.description}</p><ol class="exam-rules">${isParkingCourse(course)?`<li><b>按规定方向行驶</b><span>${course.direction==='parallel'?'倒车后入库前不得前进；入库后出库再次前进，不得倒车。':'方向依次前进、倒车、前进、倒车、前进；每段确实移动后才可换向。'}换挡前请刹停。</span></li><li><b>停稳入库 ${course.requiredParks} 次</b><span>整车在库内、车头朝图示规定方向（±15°）且速度足够低才计数；库外累计停车满 2 秒失败。</span></li><li><b>限时 30 秒</b><span>首次踩下油门开始计时。车身不能碰到判罚边线；完成入库并驶过绿色终点线即通过。</span></li>`:`<li><b>保持向前</b><span>实际倒退即判失败，挂入 R 档本身不判罚。</span></li><li><b>起步后不要停车</b><span>按下油门即开始；松油门可以滑行，但不能停下。</span></li><li><b>车身不越边界</b><span>不含后视镜的车身越界即失败；穿过绿色终点线即通过。</span></li>`}</ol><p class="vehicle-spec">Ferrari 458 Italia · 当前模拟配置<br>车身 ${VEHICLE.length.toFixed(2)} × ${VEHICLE.width.toFixed(2)} m · 轴距 ${VEHICLE.wheelbase.toFixed(3)} m<br><small>模型配套物理参数，非厂家标定数据。</small></p></div></div><div class="briefing-controls"><span><kbd>W</kbd> 油门　<kbd>S</kbd> 刹车　<kbd>A</kbd><kbd>D</kbd> 转向<br><kbd>Z</kbd> R 档　<kbd>X</kbd> N 档　<kbd>C</kbd> D 档</span><span>默认驾驶座舱 · 鼠标悬停转头；点“锁定环视”连续转头，Esc 先解锁<br>点击“回正视角”或双击场景回正；离开窗口自动暂停。</span></div></div>`;
  if(s.state==='paused'&&practice)this.overlay.innerHTML=`<div class="result-card"><div class="result-symbol">Ⅱ</div><div class="exam-eyebrow">FREE DRIVE / TAKE A BREATH</div><h1>练习已暂停</h1><p>${s.pauseReason}</p><p class="result-detail">车辆已冻结；继续后重新按下驾驶键即可出发。</p><div class="exam-bottom-actions">${btn('exit','返回项目')}${btn('retry','复位练习')}${btn('resume','继续练习 →',true)}</div></div>`;
  if(s.state==='paused'&&!practice)this.overlay.innerHTML=`<div class="result-card"><div class="result-symbol">Ⅱ</div><div class="exam-eyebrow">TAKE A BREATH</div><h1>考试已暂停</h1><p>${s.pauseReason}</p><p class="result-detail">车辆与考试判定已冻结，不会因暂停被判停车。<br>继续后请及时保持油门，或在车速仍高于停车阈值时滑行。</p><div class="exam-bottom-actions">${btn('exit','返回项目')}${btn('resume','继续考试 →',true)}</div></div>`;
  if(s.state==='result')this.overlay.innerHTML=`<div class="result-card ${s.result?.passed?'passed':'failed'}"><div class="result-symbol">${s.result?.passed?'✓':'×'}</div><div class="exam-eyebrow">${course.label} / RESULT · ${course.name}</div><h1>${s.result?.passed?'考试通过':'未通过考试'}</h1><p class="result-reason">${s.result?.reason}</p><p class="result-detail">${s.result?.passed?'每一次准确的判断，都让下一次出发更从容。':'调整节奏，观察车身与边线的位置，再试一次。'}<br>考试已结束，车辆保持冻结。</p><div class="exam-bottom-actions">${btn('exit','返回项目')}${btn('retry','重新考试 →',true)}</div></div>`;
  if(s.state!=='running')this.focusFrame=requestAnimationFrame(()=>this.overlay.querySelector<HTMLButtonElement>('.exam-primary, [data-exam="select"]')?.focus({preventScroll:true}));
  this.updateStatus();
 }
 updateStatus(){
  const s=this.session;
  if(s.mode==='practice'||!isParkingCourse(s.course)||!s.active)return;
  const value=(key:string,text:string)=>{const el=this.hud.querySelector(`[data-parking="${key}"]`);if(el&&el.textContent!==text)el.textContent=text;};
  value('remaining',Math.max(0,30-s.rules.totalElapsed).toFixed(1));
  value('stopped',s.rules.outsideStopped.toFixed(1));
  value('count',String(s.rules.parkCount));
  value('phase',`${s.rules.dirPhase+1}/5 ${s.rules.phaseLabel}`);
 }
}
